version: '3.9'
services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/go/src
    working_dir: /go/src
    command: air -c .air.toml
    networks:
      - common
    environment:
      TZ: Asia/Tokyo
      GIN_MODE: debug
      FAKE_DOMAIN: cdn-data.hackadoll.com
      # HTTP_PORT: 8080
    ports:
      - 8080:8080
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE

  nginx:
    container_name: "nginx"
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      - common

networks:
  common:
    driver: bridge